title: "Fern Gully Annals"
description: "A Mythic Bastionland Campaign Journal"
# Full path when deployed at GitHub Pages: /mythic-journals/ferngully
baseurl: "/mythic-journals/ferngully"
url: "https://astepe.github.io"
parent_site_root: "/mythic-journals"

collections:
  chapters:
    output: true
    permalink: /chapters/:slug/
    sort_by: chapter_number

defaults:
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"

markdown: kramdown
kramdown:
  input: GFM
