title: "Ballads of Braeburn"
realm_title_line1: "Ballads of"
realm_title_line2: "Braeburn"
description: "A Mythic Bastionland Campaign Journal"
# Full path when deployed at GitHub Pages: /mythic-journals/braeburn
baseurl: "/mythic-journals/braeburn"
url: "https://astepe.github.io"
parent_site_root: "/mythic-journals"

collections:
  chapters:
    output: true
    sort_by: chapter_number
    permalink: /chapters/:slug/

defaults:
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"

markdown: kramdown
kramdown:
  input: GFM
