title: "Chronicles of Cloverfell"
description: "A Mythic Bastionland Campaign Journal"
# Full path when deployed at GitHub Pages: /mythic-journals/cloverfell
baseurl: "/mythic-journals/cloverfell"
url: "https://astepe.github.io"
parent_site_root: "/mythic-journals"

collections:
  chapters:
    output: true
    permalink: /chapters/:slug/

defaults:
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"

markdown: kramdown
kramdown:
  input: GFM
